version: '{build}'
image: Visual Studio 2022
environment:
  matrix:
  - erlang_vsn: 25.0.4
install:
- ps: >-
    choco install erlang --version $env:erlang_vsn
    choco install rebar3 --version 3.13.3
build_script:
- cmd: C:\ProgramData\chocolatey\lib\rebar3\tools\rebar3.cmd compile
test_script:
- cmd: C:\ProgramData\chocolatey\lib\rebar3\tools\rebar3.cmd eunit
notifications:
- provider: Email
  to:
  - bchesneau@pm.me
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
