name: test

on:
  pull_request:

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        otp:
          - 24.2.1-1
        elixir:
          - 1.13.3
        arch:
          - amd64
          - arm64
        os:
          - ubuntu20.04
          - debian11
          - rockylinux8
          - alpine3.14
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install rebar3
        run: |
          wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
          cp ./rebar3 /usr/local/bin/rebar3

      - uses: docker/setup-buildx-action@v1

      - name: prepare buildx
        run: docker run --rm --privileged tonistiigi/binfmt:latest --install ${{ matrix.arch }}

      - name: test build
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        run: |
          IMAGE=ghcr.io/emqx/emqx-builder/5.0-8:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}
          docker run -i --rm -v $(pwd):/wd --workdir /wd --platform=linux/${{ matrix.arch }} $IMAGE bash -euc 'make'
