name: test

on:
  pull_request:

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        builder:
          - 5.1-3
        otp:
          - 25.3.2-1
        elixir:
          - 1.14.5
        os:
          - ubuntu22.04
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: test build
        env:
          IMAGE: ghcr.io/emqx/emqx-builder/${{ matrix.builder }}:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}
        run: |
          docker run --rm -u $UID -v $(pwd):/wd --workdir /wd $IMAGE bash -euc 'make'
